version: 1
dataset_name: sba
operation: download
source:
  type: http
  url: https://data.sba.gov/sites/default/files/uploaded_resources/7a_504_foia_data_dictionary.xlsx
destination:
  path: /home/rajiv/programming/kmds-dataset-util/data/raw/sba
  format: csv
