version: 1
dataset_name: seattle-police-department-911-incident-response
operation: prepare
representation: tabular
task_characterization: time_series
staging_dir: ./data/raw/seattle-police-department-911-incident-response
prepared_dataset_dir: /home/rajiv/programming/kmds-dataset-util/data/prepared/seattle-police-department-911-incident-response
output:
  path: /home/rajiv/programming/kmds-dataset-util/data/prepared/seattle-police-department-911-incident-response
  format: csv
raw_data_dictionary_path: ./data/raw/seattle-police-department-911-incident-response/data_dictionary_raw.csv
data_dictionary_path: ./data/raw/seattle-police-department-911-incident-response/data_dictionary_raw.csv
processed_data_dictionary_path: ./data/raw/seattle-police-department-911-incident-response/data_dictionary_raw.csv
